DROP TABLE IF EXISTS Medication
DROP TABLE IF EXISTS Picture
DROP TABLE IF EXISTS User
DROP TABLE IF EXISTS UserList
DROP TABLE IF EXISTS UserMedication
DROP TABLE IF EXISTS UserPictureList

CREATE TABLE Medication (MedicationID STRING NOT NULL UNIQUE PRIMARY KEY,
                        MedicationType STRING NOT NULL)
#
CREATE TABLE Picture (PictureID INT PRIMARY KEY NOT NULL UNIQUE,
                    PicturePath STRING NOT NULL)
#
CREATE TABLE User (UserID INT PRIMARY KEY NOT NULL UNIQUE ON CONFLICT ABORT, UserName STRING UNIQUE "
#                "ON CONFLICT ROLLBACK NOT NULL,
                    UserDOB DATE NOT NULL)
#
CREATE TABLE UserList (UserID INT REFERENCES User (UserID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL)
#
#
CREATE TABLE UserMedication (PrescriptionID INT PRIMARY KEY NOT NULL UNIQUE, UserID INT REFERENCES "
#                "User (UserID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, MedicationID INT REFERENCES Medication ("
#                "MedicationID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL)
#
CREATE TABLE UserPictureList (UserID INTEGER REFERENCES User (UserID) ON DELETE CASCADE ON UPDATE "
#                "CASCADE NOT NULL, PictureID INT REFERENCES Picture (PictureID) ON DELETE CASCADE ON UPDATE CASCADE "
#                "NOT NULL)